change links in maim menu
saviokmua/print-km-ua pull request #4
Opened 2018-12-11 12:19 UTC by romigos

2018-12-11 19:28 UTC, saviokmua requested changes

2018-12-11 19:28 UTC, saviokmua commented on app/views/static_pages/index.html.erb
> +        <a <%= link_to image_tag('menu_m_services.png'), services_path %>
@romigos it is not correct. Did you test it on yours end-point?

2018-12-11 19:28 UTC, saviokmua commented on app/views/static_pages/index.html.erb
> +        <a <%= link_to image_tag('menu_m_prices.png'), price_path %>
@romigos here and in below rows

2018-12-12 15:34 UTC, romigos commented on app/views/static_pages/index.html.erb
> +        <a <%= link_to image_tag('menu_m_services.png'), services_path %>
Of course i tested. Everything is working.Give me error that you get or solutions how to make this links.

2018-12-12 15:36 UTC, romigos commented on app/views/static_pages/index.html.erb
> +        <a <%= link_to image_tag('menu_m_services.png'), services_path %>
sorry i can not do it on heroku but try.

2018-12-12 16:09 UTC, saviokmua requested changes

2018-12-12 16:09 UTC, saviokmua commented on app/views/static_pages/index.html.erb
> +        <a <%= link_to image_tag('menu_m_services.png'), services_path %>
@romigos `<a <%= link_to` it is not correct. please rewrite to `<%= link_to`

2018-12-12 20:22 UTC, romigos commented
i make all changes and now i know how to pull changes in another branch. Thanks

2018-12-12 20:23 UTC, romigos commented
sorry to push changes.

2018-12-12 20:24 UTC, saviokmua approved these changes

2018-12-12 20:24 UTC, merged