create admin links
saviokmua/print-km-ua pull request #8
Opened 2018-12-16 12:53 UTC by romigos

2018-12-17 20:39 UTC, saviokmua requested changes
@romigos why you deleted `config/database.yml.example`?

2018-12-18 10:54 UTC, romigos commented
Sorry, have some trouble in the mail. I rename this file on database.yml.

2018-12-18 13:46 UTC, romigos commented
look is it correct?

2018-12-18 13:51 UTC, saviokmua commented
yes. thanks

2018-12-18 13:51 UTC, merged